"""Base policy abstract class and policy decision models."""
from abc import ABC, abstractmethod
from typing import Any, List, Optional
from pydantic import BaseModel, ConfigDict, Field

from intelligence.context import ObservableRecoveryContext
from intelligence.schemas import StructuredDiagnosis
from simulator.config import SimulatedActionType


class PolicyDecision(BaseModel):
    """Decision output generated by an autonomous policy for a given scenario."""
    model_config = ConfigDict(extra="forbid")

    action_type: SimulatedActionType = Field(..., description="Action chosen by the policy")
    confidence: float = Field(default=1.0, ge=0.0, le=1.0, description="Confidence score [0.0, 1.0]")
    economic_confidence: float = Field(default=1.0, ge=0.0, le=1.0, description="Confidence in expected net recovery uplift")
    execution_state_validity: float = Field(default=1.0, ge=0.0, le=1.0, description="Validity score of execution state")
    rationale: str = Field(..., min_length=1, description="Audit reasoning behind the policy decision")
    policy_name: str = Field(..., description="Identifier of the executing policy")
    reason_codes: List[str] = Field(default_factory=list, description="Machine-readable audit reason tags")
    expected_net_value_paise: Optional[int] = Field(default=None, description="Estimated net recovery in paise")
    expected_incremental_value_paise: Optional[int] = Field(default=None, description="Estimated incremental uplift in paise")
    timing_window: Optional[str] = Field(default=None, description="Timing window bucket (e.g. IMMEDIATE, PLUS_2H, PLUS_6H)")
    delay_seconds: int = Field(default=0, ge=0, description="Scheduled delay in seconds")
    diagnosis: Optional[StructuredDiagnosis] = Field(default=None, description="Structured diagnosis utilized in decisioning")
    strategy_source: Optional[str] = Field(default=None, description="Strategy provider source (e.g. deterministic_offline, llm_structured, cached_llm, deterministic_fallback)")
    strategy_proposal: Optional[Any] = Field(default=None, description="Strategy proposal utilized in decisioning")


class BasePolicy(ABC):
    """Abstract base class for all dunning recovery policies."""

    def __init__(self, name: str, description: str) -> None:
        self.name = name
        self.description = description

    @abstractmethod
    def decide(
        self,
        context: ObservableRecoveryContext,
        diagnosis: Optional[StructuredDiagnosis] = None,
    ) -> PolicyDecision:
        """Evaluate a scenario using ONLY sanitized observable recovery context and structured diagnosis.

        Guarantees:
        - Policies receive ObservableRecoveryContext (no hidden potential outcomes, archetypes, or true failure classes).
        - Policies use StructuredDiagnosis for semantic reasoning.
        """
        pass
