"""Base policy abstract class and policy decision models."""
from abc import ABC, abstractmethod
from typing import List, Optional
from pydantic import BaseModel, ConfigDict, Field

from policy.public_view import PublicScenarioView
from simulator.config import SimulatedActionType


class PolicyDecision(BaseModel):
    """Decision output generated by an autonomous policy for a given scenario."""
    model_config = ConfigDict(extra="forbid")

    action_type: SimulatedActionType = Field(..., description="Action chosen by the policy")
    confidence: float = Field(default=1.0, ge=0.0, le=1.0, description="Confidence score [0.0, 1.0]")
    rationale: str = Field(..., min_length=1, description="Audit reasoning behind the policy decision")
    policy_name: str = Field(..., description="Identifier of the executing policy")
    reason_codes: List[str] = Field(default_factory=list, description="Machine-readable audit reason tags")
    expected_net_value_paise: Optional[int] = Field(default=None, description="Estimated net recovery in paise")
    expected_incremental_value_paise: Optional[int] = Field(default=None, description="Estimated incremental uplift in paise")


class BasePolicy(ABC):
    """Abstract base class for all dunning recovery policies."""

    def __init__(self, name: str, description: str) -> None:
        self.name = name
        self.description = description

    @abstractmethod
    def decide(self, scenario: PublicScenarioView) -> PolicyDecision:
        """Evaluate a scenario using ONLY sanitized public domain event data.

        Guarantees:
        - Policies receive PublicScenarioView.
        - Policies cannot inspect hidden counterfactual outcomes or latent customer archetypes.
        """
        pass
