"""Structured diagnosis data contracts and taxonomy definitions for RecoveryOS."""
from enum import Enum
from typing import List, Optional
from pydantic import BaseModel, ConfigDict, Field

from simulator.config import SimulatedActionType


class DiagnosisLabel(str, Enum):
    """Canonical root-cause diagnosis taxonomy inferred strictly from observable context."""
    TRANSIENT_GATEWAY_FAILURE = "transient_gateway_failure"
    INSUFFICIENT_FUNDS = "insufficient_funds"
    EXPIRED_PAYMENT_METHOD = "expired_payment_method"
    AUTHENTICATION_FAILURE = "authentication_failure"
    MANDATE_ISSUE = "mandate_issue"
    CUSTOMER_ABANDONMENT = "customer_abandonment"
    SUBSCRIPTION_PAYMENT_FAILURE = "subscription_payment_failure"
    OVERDUE_INVOICE = "overdue_invoice"
    UNKNOWN_FAILURE = "unknown_failure"


class StructuredDiagnosis(BaseModel):
    """Schema-validated, explainable diagnosis produced by an intelligence provider.

    Contains machine-readable evidence, confidence calibration, action recommendations,
    and fallback provenance.
    """
    model_config = ConfigDict(extra="forbid")

    diagnosis_label: DiagnosisLabel = Field(..., description="Root cause diagnosis category")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Calibrated confidence score [0.0, 1.0]")
    evidence_codes: List[str] = Field(default_factory=list, description="Observable evidence codes justifying diagnosis")
    uncertainties: List[str] = Field(default_factory=list, description="Identified risk factors or ambiguities")
    recommended_candidate_actions: List[SimulatedActionType] = Field(
        default_factory=list, description="Candidate recovery actions recommended by diagnosis"
    )
    recommended_timing_hint: Optional[str] = Field(
        default=None, description="Suggested execution timing hint (e.g. 'immediate', 'delay_2h', 'delay_6h')"
    )
    human_review_required: bool = Field(default=False, description="Flag requesting merchant operator review")
    abstain_recommended: bool = Field(default=False, description="Flag indicating intervention is likely value-destructive")
    rationale: str = Field(..., min_length=1, description="Audit rationale explaining the diagnostic inference")
    diagnosis_source: str = Field(
        default="deterministic_offline",
        description="Provenance source of diagnosis ('deterministic_offline', 'llm_structured', 'deterministic_fallback')",
    )
    model_version: Optional[str] = Field(default="v1.0", description="Diagnosis model or provider version")


class StrategyCandidateProposal(BaseModel):
    """Structured candidate recovery intervention proposal generated by Strategy Agent."""
    model_config = ConfigDict(extra="forbid")

    action_type: SimulatedActionType = Field(..., description="Proposed recovery intervention")
    mechanism: str = Field(..., description="Intervention mechanism category (e.g. 'retry', 'payment_link', 'reminder', 'no_action', 'human_review')")
    rationale: str = Field(..., min_length=1, description="Strategic reasoning justifying this intervention")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Confidence in strategy viability")
    supporting_evidence: List[str] = Field(default_factory=list, description="Evidence codes and memory references supporting candidate")
    risk_notes: List[str] = Field(default_factory=list, description="Identified execution risks or constraints")
    preferred_timing_direction: Optional[str] = Field(default=None, description="Preferred timing direction (e.g. 'immediate', 'delay_6h')")
    preferred_channel: Optional[str] = Field(default=None, description="Preferred communication channel if applicable")
    why_better_than_abstain: str = Field(default="", description="Justification why this intervention beats zero-cost baseline abstention")
    why_alternative_inferior: str = Field(default="", description="Justification why alternatives are less optimal")
    is_abstention: bool = Field(default=False, description="Whether this candidate represents deliberate non-intervention")


class StrategyProposal(BaseModel):
    """Comprehensive strategy reasoning output from the RecoveryStrategyAgent."""
    model_config = ConfigDict(extra="forbid")

    proposals: List[StrategyCandidateProposal] = Field(default_factory=list, description="Ranked strategy candidates")
    primary_recommendation: SimulatedActionType = Field(..., description="Top recommended candidate action")
    strategic_summary: str = Field(..., description="High-level synthesis of strategy reasoning")
    strategy_source: str = Field(default="llm_reasoner", description="Source of strategy proposal ('llm_reasoner', 'deterministic_fallback')")
    model_version: Optional[str] = Field(default="openai/gpt-oss-120b", description="Model version used for strategy")

